### ISSUE TITLE
A question :)

### ISSUE THREAD

**Issue by IDhammaI** [Nippaku-Zanmu/meteor-translation-addon#2]
First of all, I'm very sorry that I posted unrelated issues regarding this project：
May I ask if your warehouse repo is still open？
https://github.com/Nippaku-Zanmu/seija-printer-easy  About the printer
![image](https://github.com/user-attachments/assets/b5d2628d-4358-4f67-b4d1-f21ee8ef262d)

I hope to obtain the source code of this mod..plz...

**Comment by Nippaku-Zanmu** [comment]
我暂时并不想再次开放这个项目 因为之前有人使用我的开源代码开发商业项目且违背GPL协议 并且这只是一个削弱版
也许等到之后我的打印机项目趋于完美后我可能会把它开源

I don't want to open this project again for a while, because there have been people who have used my open source code to develop commercial projects that violate the GPL, and this is only a weakened version
Maybe I'll open source it later when my printer project is perfected
